language: java

addons:
  ssh_known_hosts: ec2-3-122-55-117.eu-central-1.compute.amazonaws.com

before_deploy:
  - openssl aes-256-cbc -K $encrypted_a4b38815624c_key -iv $encrypted_a4b38815624c_iv -in ./rsa.enc -out ./rsa_dec -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./rsa_dec
  - ssh-add ./rsa_dec
#- ls $TRAVIS_BUILD_DIR/backend-http/

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script: scp -4 $TRAVIS_BUILD_DIR/backend-http/target/backend-http-0.1-SNAPSHOT.jar ubuntu@ec2-3-122-55-117.eu-central-1.compute.amazonaws.com:build.jar
